"""Curated public API for the deep_mkv_gen package.

Power-user and experimental helpers remain available from subpackages such as
`deep_mkv_gen.core`, `deep_mkv_gen.providers`, and `deep_mkv_gen.analysis`.
"""

from ._version import __version__
from .core import (
    CheckpointConfig,
    EvalConfig,
    KConfig,
    DeepMKVGen,
    DeepMKVGenConfig,
    RunConfig,
    RunHooks,
    RunResult,
    SourceSampler,
    StageRecord,
    TargetSampler,
    TrainConfig,
    Y0Net,
    ZNet,
    estimate_kl_knn_from_samples,
    fit,
    make_time_grid,
    sample,
    sample_with_snapshots,
    transport,
    transport_with_snapshots,
    sliced_w2_sq,
    wasserstein2,
)
from .providers import (
    DSMScoreConfig,
    DSMScoreModel,
    GeomLossW2ProviderConfig,
    HybridProviderConfig,
    HybridProviderSpec,
    KLProviderSpec,
    KLRatioScoreConfig,
    KLScoreDifferenceConfig,
    ProviderSpec,
    W2ProviderSpec,
)

__all__ = [
    "CheckpointConfig",
    "DSMScoreConfig",
    "DSMScoreModel",
    "EvalConfig",
    "GeomLossW2ProviderConfig",
    "HybridProviderConfig",
    "HybridProviderSpec",
    "KConfig",
    "KLProviderSpec",
    "KLRatioScoreConfig",
    "KLScoreDifferenceConfig",
    "ProviderSpec",
    "W2ProviderSpec",
    "DeepMKVGen",
    "DeepMKVGenConfig",
    "RunConfig",
    "RunHooks",
    "RunResult",
    "SourceSampler",
    "StageRecord",
    "TargetSampler",
    "TrainConfig",
    "Y0Net",
    "ZNet",
    "__version__",
    "estimate_kl_knn_from_samples",
    "fit",
    "make_time_grid",
    "sample",
    "sample_with_snapshots",
    "transport",
    "transport_with_snapshots",
    "sliced_w2_sq",
    "wasserstein2",
]
